# Generated by Django 4.2.7 on 2023-11-21 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_queue_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='participants',
            field=models.ManyToManyField(to='users.participant'),
        ),
    ]
