# Generated by Django 4.2.7 on 2023-11-21 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_queue_current_pos'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='queue',
            name='participants',
            field=models.ManyToManyField(blank=True, null=True, to='users.participant'),
        ),
    ]
