# Generated by Django 4.2.7 on 2024-04-11 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_participant_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
