# Generated by Django 4.2.7 on 2024-04-11 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_queue_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='waiting_time',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
