# Generated by Django 4.2.7 on 2024-04-16 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_participant_waiting_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='max_service',
            field=models.IntegerField(blank=True, default=20, null=True),
        ),
        migrations.AddField(
            model_name='queue',
            name='min_service',
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
        migrations.AddField(
            model_name='queue',
            name='num_servers',
            field=models.IntegerField(blank=True, default=2, null=True),
        ),
    ]
