# Generated by Django 4.2.7 on 2024-04-18 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_organization_org_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='org_id',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
