# Generated by Django 4.2.7 on 2024-04-19 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_queue_service_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='service_name',
            field=models.CharField(default='', max_length=100, null=True, unique=True),
        ),
    ]
