# Generated by Django 4.2.7 on 2024-04-19 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_queue_service_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='WaitingTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waiting_time', models.FloatField(blank=True, default=0, null=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('queue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.queue')),
            ],
        ),
    ]
