# Generated by Django 4.2.7 on 2024-04-19 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_queue_description_waitingtime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waitingtime',
            name='queue',
        ),
        migrations.AddField(
            model_name='waitingtime',
            name='org_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='waitingtime',
            name='service_name',
            field=models.CharField(default='', max_length=100, null=True, unique=True),
        ),
    ]
