# Generated by Django 4.2.7 on 2024-04-19 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_remove_waitingtime_queue_waitingtime_org_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waitingtime',
            name='org_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
