# Generated by Django 4.2.7 on 2024-04-19 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_waitingtime_org_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waitingtime',
            name='service_name',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
